version: '3'
services:
  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - "11211:11211"
  testsamlidp_idp:
    image: idp
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: acc.justitieconnect.eminvenj.nl
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://acc.development.justitieconnect.eminvenj.nl/saml2/acs/
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://acc.development.justitieconnect.eminvenj.nl/saml/ls/
      SIMPLESAMLPHP_ADMIN_PASSWORD: test
      SIMPLESAMLPHP_SECRET_SALT: salt
    ports:
      - "8080:8080"
      - "8443:8443"
    #volumes:
    #- /users.php:/var/www/simplesamlphp/config/simplesamlphp/authsources.php
